TRIPPIFY_DB_USER = 'trippify'
TRIPPIFY_DB_PASSWORD = 'trippify1234'
TRIPPIFY_DB_DB = 'trippify'
TRIPPIFY_DB_HOST = 'localhost'
TRIPPIFY_DB_PORT = 5432

MAPS_GEO_CODING_API_KEY = 'AIzaSyBUl98DdV0U05pu7spTcP-RIB_qoCkNcYU'


__all__ = [
    'TRIPPIFY_DB_USER',
    'TRIPPIFY_DB_PASSWORD',
    'TRIPPIFY_DB_DB',
    'TRIPPIFY_DB_HOST',
    'TRIPPIFY_DB_PORT',
    'MAPS_GEO_CODING_API_KEY'
]
